GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6297fdd825f517f534853838

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Amazing person",
  "subscribedToChannel": "WebDevSimplified"
}